# Generated by Django 5.2.14 on 2026-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.IntegerField(blank=True, null=True)),
                ('tytul', models.CharField(max_length=255)),
                ('min_graczy', models.IntegerField(blank=True, null=True)),
                ('max_graczy', models.IntegerField(blank=True, null=True)),
                ('czas_gry', models.IntegerField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('publikacja', models.IntegerField(blank=True, null=True)),
                ('dodany', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
